use latest pipeline

diff --git a/.github/workflows/push.yml b/.github/workflows/push.yml
--- a/.github/workflows/push.yml
+++ b/.github/workflows/push.yml
@@ -1,5 +1,6 @@
 name: GitHub Actions
-on: [push]
+on: [ push ]
+concurrency: ci-${{ github.ref }} # to avoid tag collisions in the ECR
 env:
   APP_IMAGE: keboola-ex-storage
   KBC_DEVELOPERPORTAL_APP: "keboola.ex-storage"
@@ -7,37 +8,106 @@ env:
   KBC_DEVELOPERPORTAL_USERNAME: "keboola+ex_storage_gh_actions"
   KBC_DEVELOPERPORTAL_PASSWORD: ${{ secrets.KBC_DEVELOPERPORTAL_PASSWORD }}
   # https://connection.keboola.com/admin/projects/2703/extractors/keboola.ex-storage/764729155
-  KBC_APP_TEST_CONFIG_ID: 764729155
+  KBC_TEST_PROJECT_CONFIGS: 764729155
   KBC_TEST_BUCKET: in.c-ex-storage
   KBC_TEST_URL: https://connection.keboola.com/
   KBC_TEST_TOKEN: ${{ secrets.KBC_TEST_TOKEN }}
   KBC_TEST_WRITE_TOKEN: ${{ secrets.KBC_TEST_WRITE_TOKEN }}
   KBC_STORAGE_TOKEN: ${{ secrets.KBC_STORAGE_TOKEN }}
 jobs:
-  Build:
+  build:
     runs-on: ubuntu-latest
+    outputs:
+      app_image_tag: ${{ steps.tag.outputs.app_image_tag }}
+      is_semantic_tag: ${{ steps.tag.outputs.is_semantic_tag }}
     steps:
-      - name: Check out the repo
+      -
+        name: Check out the repo
         uses: actions/checkout@v2
-      - name: Print Docker version
-        run: |
-          docker -v
-      - name: Docker login
+      -
+        name: Print Docker version
+        run: docker -v
+      -
+        name: Docker login
         if: env.DOCKERHUB_TOKEN
         run: docker login --username "$DOCKERHUB_USER" --password "$DOCKERHUB_TOKEN"
-      - name: Run tests and build image
+      -
+        name: Build image
+        run: docker build -t $APP_IMAGE .
+      -
+        name: Set image tag
+        id: tag
         run: |
-          docker build -t $APP_IMAGE .
-          docker run -e KBC_TEST_TOKEN -e KBC_TEST_WRITE_TOKEN -e KBC_TEST_URL -e KBC_TEST_BUCKET $APP_IMAGE composer ci
-      - name: Push image to ECR
-        run: |
-          docker pull quay.io/keboola/developer-portal-cli-v2:latest
-          export REPOSITORY=`docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-repository $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP`
-          docker tag $APP_IMAGE:latest $REPOSITORY:test
-          eval $(docker run --rm -e KBC_DEVELOPERPORTAL_USERNAME -e KBC_DEVELOPERPORTAL_PASSWORD -e KBC_DEVELOPERPORTAL_URL quay.io/keboola/developer-portal-cli-v2:latest ecr:get-login $KBC_DEVELOPERPORTAL_VENDOR $KBC_DEVELOPERPORTAL_APP)
-          docker push $REPOSITORY:test
-          docker pull quay.io/keboola/syrup-cli:latest
-          docker run --rm -e KBC_STORAGE_TOKEN quay.io/keboola/syrup-cli:latest run-job $KBC_DEVELOPERPORTAL_APP $KBC_APP_TEST_CONFIG_ID test
-      - name: Deploy
-        if: startsWith(github.ref, 'refs/tags/')
-        run: ./deploy.sh
+          TAG="${GITHUB_REF##*/}"
+          IS_SEMANTIC_TAG=$(echo "$TAG" | grep -q '^v\?[0-9]\+\.[0-9]\+\.[0-9]\+$' && echo true || echo false)
+          echo "Tag = '$TAG', is semantic tag = '$IS_SEMANTIC_TAG'"
+          echo "::set-output name=app_image_tag::$TAG"
+          echo "::set-output name=is_semantic_tag::$IS_SEMANTIC_TAG"
+      -
+        name: Push image to ECR
+        uses: keboola/action-push-to-ecr@master
+        with:
+          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
+          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP }}
+          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
+          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
+          tag: ${{ steps.tag.outputs.app_image_tag }}
+          push_latest: ${{ steps.tag.outputs.is_semantic_tag }}
+          source_image: ${{ env.APP_IMAGE}}
+
+  tests:
+    needs: build
+    runs-on: ubuntu-latest
+    # strategy:
+    #   fail-fast: false
+    #   matrix: ...
+    steps:
+      -
+        name: Check out the repo
+        uses: actions/checkout@v2
+      -
+        name: Pull image from ECR
+        uses: keboola/action-pull-from-ecr@master
+        with:
+          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
+          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP }}
+          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
+          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
+          tag: ${{ needs.build.outputs.app_image_tag }}
+          target_image: ${{ env.APP_IMAGE}}
+          tag_as_latest: true
+      -
+        name: Run tests
+        run: docker run -e KBC_TEST_TOKEN -e KBC_TEST_WRITE_TOKEN -e KBC_TEST_URL -e KBC_TEST_BUCKET ${{env.APP_IMAGE}} composer ci
+
+  tests-in-kbc:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      -
+        name: Run KBC test jobs
+        if: env.KBC_STORAGE_TOKEN && env.KBC_TEST_PROJECT_CONFIGS
+        uses: keboola/action-run-configs-parallel@master
+        with:
+          token: ${{ env.KBC_STORAGE_TOKEN }}
+          componentId: ${{ env.KBC_DEVELOPERPORTAL_APP }}
+          tag: ${{ needs.build.outputs.app_image_tag }}
+          configs: ${{ env.KBC_TEST_PROJECT_CONFIGS }}
+
+  deploy:
+    needs:
+      - build
+      - tests
+      - tests-in-kbc
+    runs-on: ubuntu-latest
+    if: startsWith(github.ref, 'refs/tags/') && needs.build.outputs.is_semantic_tag == 'true'
+    steps:
+      -
+        name: Set tag in the Deloper Portal
+        uses: keboola/action-set-tag-developer-portal@master
+        with:
+          vendor: ${{ env.KBC_DEVELOPERPORTAL_VENDOR }}
+          app_id: ${{ env.KBC_DEVELOPERPORTAL_APP }}
+          username: ${{ env.KBC_DEVELOPERPORTAL_USERNAME }}
+          password: ${{ env.KBC_DEVELOPERPORTAL_PASSWORD }}
+          tag: ${{ needs.build.outputs.app_image_tag }}
